//
//  MovieDetailInteractor.swift
//  Movies
//
//  Created ilker on 8.04.2020.
//  Copyright © 2020 ilker. All rights reserved.
//
//  Template generated by Suat Karakusoglu
//

import UIKit

final class MovieDetailInteractor: Interactor {
    
    typealias Response = MovieDetailInteractorResponse
    typealias Request = MovieDetailInteractorRequest
    
    var responseListener: AnyResponseListener<MovieDetailInteractorResponse>?
    
    var apiServices = MoviesApiService()
    var movieId: Int
    
    init(movieId: Int) {
        self.movieId = movieId
    }
    
    func handle(request: MovieDetailInteractorRequest) {
        switch request {
        case .getMovieDetail:
            apiServices.getMovieDetail(movieId: movieId, completionHandler:{ (response,error) in
                guard let response = response else {
                    self.responseListener?.handle(response: .getMovieDetailResponseFailed)
                    return
                }
                self.responseListener?.handle(response: .getMovieDetailResponse(movieDetail: response))
            })
        @unknown default:
            print("InteractorRequest should be handled at \(#function)")
        }
    }
}
