//
//  HomePageArenaType.swift
//  Movies
//
//  Created ilker on 8.04.2020.
//  Copyright © 2020 ilker. All rights reserved.
//
//  Template generated by Suat Karakusoglu
//

import UIKit.UIViewController
import UIKit.UINavigationController

extension ArenaType
{
    func buildHomePage() -> UIViewController {
        let viewController = HomePageViewController()
        let presenter = HomePagePresenter()
        let interactor = HomePageInteractor()
        
        self.build(
            view: viewController,
            presenter: presenter,
            interactor: interactor)
        
        presenter.router = HomePageRouter(arenaPresenter: viewController)
        
        return viewController
    }
}
